default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: 5
  database: reactjs-sample
  host: localhost
  username: root
  password: champion

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
